// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVETRAIN_H
#define DRIVETRAIN_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

class Drivetrain: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* rearRight;
	SpeedController* frontLeft;
	SpeedController* rearLeft;
	SpeedController* frontRight;
	RobotDrive* robotDrive;
	Gyro* driveGyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	AnalogInput* leftSonar;
	AnalogInput* rightSonar;
	double CorrectionAngle(double correctionConstant);
	void ResetHeading();
	void DriveOnHeading(double velocity, double correctionConstant);
	Drivetrain();
	void InitDefaultCommand();
	void DriveTeleop(double x, double y, double r);
	void toggleFastMode();
	double xScalar;
	double yScalar;
	double rotationScalar;
	double correctionAngle;
	bool quadraticScaling;
	bool fastMode;
	bool fastModeMultiplier;
};

#endif
