#include "BackupToAutonZone.h"
#include "Timer.h"

BackupToAutonZone::BackupToAutonZone() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	duration = .5;
}
void BackupToAutonZone::Initialize() {
//	Robot::drivetrain->ResetHeading();
	startTime = Timer::GetFPGATimestamp();
}
void BackupToAutonZone::Execute() {
	Robot::drivetrain->DriveOnHeading(1);
}
bool BackupToAutonZone::IsFinished() {
	return Timer::GetFPGATimestamp() > startTime + duration;
}
void BackupToAutonZone::End() {
	Robot::drivetrain->DriveOnHeading(0.0);
}
void BackupToAutonZone::Interrupted() {
}
