#include "DriveForward.h"
#include "../Subsystems/StepDetectorator.h"

DriveForward::DriveForward() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	startTime = 0.0;
	timeOut = 0.0;
}
void DriveForward::Initialize() {
	Robot::drivetrain->ResetHeading();
	startTime = Timer::GetFPGATimestamp();
	timeOut = 3.0;
}
void DriveForward::Execute() {
	Robot::drivetrain->DriveOnHeading(-0.3);
}
bool DriveForward::IsFinished() {
	return 	Robot::stepDetectorator->IsAtStep() || Timer::GetFPGATimestamp() > startTime + timeOut;
}
void DriveForward::End() {
	Robot::drivetrain->DriveOnHeading(0.0);
	puts("drive forward ended");
}
void DriveForward::Interrupted() {
}
