// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "PIDLift.h"
#include "../OI.h"

PIDLift::PIDLift() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void PIDLift::Initialize() {
//	liftPIDController = new PIDController(Robot::oi->p, Robot::oi->i, Robot::oi->d, Robot::lift->encoder, Robot::lift->speedController1);
//	liftPIDController->SetSetpoint(200);
//	liftPIDController->Disable();
}

// Called repeatedly when this Command is scheduled to run
void PIDLift::Execute() {
//	liftPIDController->Enable();

	
}

// Make this return true when this Command no longer needs to run execute()
bool PIDLift::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void PIDLift::End() {
//	liftPIDController->Disable();
//	delete liftPIDController;
//	liftPIDController = NULL;
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void PIDLift::Interrupted() {

}
