// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RaiseOneTote.h"

RaiseOneTote::RaiseOneTote() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::lift);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void RaiseOneTote::Initialize() {
	durationNumber = 400;
	limitSwitchTripped = false;
	Robot::lift->encoder->Reset();

}

// Called repeatedly when this Command is scheduled to run
void RaiseOneTote::Execute() {
	Robot::lift->speedController1->Set(.2);
	Robot::lift->speedController2->Set(.2);
	printf("encoder! %f", fabs(Robot::lift->encoder->GetDistance()));
	if(!limitSwitchTripped) {
	limitSwitchTripped = Robot::lift->limitSwitch->Get();
	}
}

// Make this return true when this Command no longer needs to run execute()
bool RaiseOneTote::IsFinished() {
	bool done = false;
	if(Robot::lift->limitSwitch->Get()) {
		startNumber = 	Robot::lift->encoder->GetDistance();
		printf("start number %f", startNumber);
	}
	if(limitSwitchTripped){
	printf("current Number %f", currentNumber);
	currentNumber = Robot::lift->encoder->GetDistance();
	done =  currentNumber+durationNumber <= startNumber;
	}
}

// Called once after isFinished returns true
void RaiseOneTote::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void RaiseOneTote::Interrupted() {

}
