// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROTATEWINGS_H
#define ROTATEWINGS_H

class RotateWings;
#include "../Robot.h"
#include "Commands/Subsystem.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class RotateWings: public Command {
public:
	RotateWings(float direction, float time,float wait);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
	bool hasSetAngle;
	float setAngle;
	float direction;
	float startTime;
	float time;
	float wait;
};

#endif
