// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AlignWithStep.h"
#include "Commands/AutonJerky.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/BackupToAutonZone.h"
#include "Commands/DriveForward.h"
#include "Commands/DriveTeleop.h"
#include "Commands/GatherCans.h"
#include "Commands/LiftTeleop.h"
#include "Commands/ResetLift.h"
#include "Commands/RetractLeftWing.h"
#include "Commands/RetractRightWing.h"
#include "Commands/PIDLift.h"
#include "Commands/RetractWings.h"
#include "Commands/RotateWings.h"
#include "Commands/RunLift.h"
#include "Commands/ShiftToHighGear.h"
#include "Commands/ShiftToLowGear.h"
#include "Commands/WingsTeleop.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	joystick1 = new Joystick(0);
	joystick2 = new Joystick(1);
	
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("DriveForward", new DriveForward());

	SmartDashboard::PutData("AlignWithStep", new AlignWithStep());

	SmartDashboard::PutData("BackupToAutonZone", new BackupToAutonZone());

	SmartDashboard::PutData("GatherCans", new GatherCans());

	SmartDashboard::PutData("RetractWings", new RetractWings());

	SmartDashboard::PutData("DriveTeleop", new DriveTeleop());

	SmartDashboard::PutData("LiftTeleop", new LiftTeleop());

	SmartDashboard::PutData("WingsTeleop", new WingsTeleop());

	SmartDashboard::PutData("ShiftToHighGear", new ShiftToHighGear());

	SmartDashboard::PutData("ShiftToLowGear", new ShiftToLowGear());

	SmartDashboard::PutData("AutonJerky", new AutonJerky());

//	SmartDashboard::PutData("RetractRightWing", new RetractRightWing());
//
//	SmartDashboard::PutData("RetractLeftWing", new RetractLeftWing());
	SmartDashboard::PutData("PIDLift", new PIDLift());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	//smartdashboard stuff

	SmartDashboard::PutNumber("autonJerkyDuration", 0.5);
	SmartDashboard::PutNumber("autonJerkySpeed", 1);

	SmartDashboard::PutNumber("backupToAutonZoneDuration",2);
	SmartDashboard::PutNumber("backupToAutonZoneSpeed",0.4);
	SmartDashboard::PutNumber("backupToAutonZoneAngle",15);

	SmartDashboard::PutNumber("driveForwardTimeout", 3);
	SmartDashboard::PutNumber("driveForwardSpeed", 0.15);

	SmartDashboard::PutNumber("gatherCansRotateSpeed",0.2);
	SmartDashboard::PutNumber("gatherCansRotateDuration",2);

	SmartDashboard::PutNumber("lowerOneToteDuration",700);
	SmartDashboard::PutNumber("lowerOneToteSpeed",-0.5);


	SmartDashboard::PutNumber("pidLiftP",1);
	SmartDashboard::PutNumber("pidLiftI",0);
	SmartDashboard::PutNumber("pidLiftD",0);
	SmartDashboard::PutNumber("pidLiftSetPoint",300);

	SmartDashboard::PutNumber("raiseOneToteDuration",700);
	SmartDashboard::PutNumber("raiseOneToteSpeed",0.5);

	SmartDashboard::PutNumber("retractWingsDuration",1.5);
	SmartDashboard::PutNumber("retractWingsSpeed",0.2);


}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getJoystick1() {
	return joystick1;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

