// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::drivetrainSpeedController4 = NULL;
SpeedController* RobotMap::drivetrainSpeedController1 = NULL;
SpeedController* RobotMap::drivetrainSpeedController2 = NULL;
SpeedController* RobotMap::drivetrainSpeedController3 = NULL;
RobotDrive* RobotMap::drivetrainrobotDrive = NULL;
Gyro* RobotMap::drivetraindriveGyro = NULL;
AnalogInput* RobotMap::drivetrainsonar = NULL;
SpeedController* RobotMap::liftSpeedController1 = NULL;
SpeedController* RobotMap::liftSpeedController2 = NULL;
RobotDrive* RobotMap::liftliftDrive = NULL;
Encoder* RobotMap::liftencoder = NULL;
DigitalInput* RobotMap::liftlimitSwitch = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	drivetrainSpeedController4 = new Talon(3);
	lw->AddActuator("Drivetrain", "Speed Controller 4", (Talon*) drivetrainSpeedController4);
	
	drivetrainSpeedController1 = new Talon(0);
	lw->AddActuator("Drivetrain", "Speed Controller 1", (Talon*) drivetrainSpeedController1);
	
	drivetrainSpeedController2 = new Talon(1);
	lw->AddActuator("Drivetrain", "Speed Controller 2", (Talon*) drivetrainSpeedController2);
	
	drivetrainSpeedController3 = new Talon(2);
	lw->AddActuator("Drivetrain", "Speed Controller 3", (Talon*) drivetrainSpeedController3);
	
	drivetrainrobotDrive = new RobotDrive(drivetrainSpeedController1, drivetrainSpeedController2,
              drivetrainSpeedController3, drivetrainSpeedController4);
	
	drivetrainrobotDrive->SetSafetyEnabled(true);
        drivetrainrobotDrive->SetExpiration(0.1);
        drivetrainrobotDrive->SetSensitivity(0.5);
        drivetrainrobotDrive->SetMaxOutput(1.0);

	drivetraindriveGyro = new Gyro(1);
	lw->AddSensor("Drivetrain", "driveGyro", drivetraindriveGyro);
	drivetraindriveGyro->SetSensitivity(0.007);
	drivetrainsonar = new AnalogInput(2);
	lw->AddSensor("Drivetrain", "sonar", drivetrainsonar);
	
	liftSpeedController1 = new Talon(4);
	lw->AddActuator("Lift", "Speed Controller 1", (Talon*) liftSpeedController1);
	
	liftSpeedController2 = new Talon(5);
	lw->AddActuator("Lift", "Speed Controller 2", (Talon*) liftSpeedController2);
	
	liftliftDrive = new RobotDrive(liftSpeedController1, liftSpeedController2);
	
	liftliftDrive->SetSafetyEnabled(true);
        liftliftDrive->SetExpiration(0.1);
        liftliftDrive->SetSensitivity(0.5);
        liftliftDrive->SetMaxOutput(1.0);
        

	liftencoder = new Encoder(2, 3, false, Encoder::k4X);
	lw->AddSensor("Lift", "encoder", liftencoder);
	liftencoder->SetDistancePerPulse(1.0);
        liftencoder->SetPIDSourceParameter(Encoder::kRate);
	liftlimitSwitch = new DigitalInput(4);
	lw->AddSensor("Lift", "limitSwitch", liftlimitSwitch);
	


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
